### ISSUE TITLE
Cross plugin bug

### ISSUE THREAD

**Issue by seqizz** [evolvingweb/redmine-my-page-queries#1]
I know this is not an active repo, but here is a bug :)

Can't use the plugin with "redmine_tags"

```
Started GET "/my/page" for 85.105.100.85 at 2014-02-04 15:30:19 +0200
Processing by MyController#page as HTML
  Current user: xxxxx (id=4)
  Rendered plugins/redmine_my_page_queries/app/views/my/_query_block.html.erb (556.6ms)
  Rendered plugins/redmine_my_page_queries/app/views/my/page.html.erb within layouts/base (595.3ms)
Completed 500 Internal Server Error in 607.7ms

ActionView::Template::Error (undefined method `render_tag_link' for #<#<Class:0x000000046835e0>:0x007f1b09aa2c58>):
    34:             <% previous_group = group %>
    35:           <% end %>
    36:           <tr id="issue-<%= issue.id %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
    37:             <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", issue.id, false, :id => nil) %></td>
    38:             <%= raw query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, issue)}</td>"}.join %>
    39:           </tr>
    40:           <% query.block_columns.each do |column|
  app/helpers/issues_helper.rb:29:in `block in issue_list'
  app/helpers/issues_helper.rb:25:in `each'
  app/helpers/issues_helper.rb:25:in `issue_list'
```

**Comment by dergachev** [comment]
I'm a bit puzzled by the stack trace. Which exact version of redmine and redmine_tags are you using? What makes you think it's related to redmine-my-page-queries? Also is this issue relevant: https://github.com/ixti/redmine_tags/issues/14

If I ever get around to upgrading this plugin to the latest version of redmine (can't promise when!), I'll definitely take a look at this. 

Thanks for reporting!

**Comment by seqizz** [comment]
I'm not sure which one is caused and/or can do something. redmine-mypage-queries making the crash if an unknown column (like tags) wants to come to mypage.

```
Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  redmine_extended_watchers      0.0.4
  redmine_helpdesk               0.0.8
  redmine_screenshot_paste       2.1.0
  redmine_tags                   2.1.0
```
